import unittest

from book_writer import gui


class TestGui(unittest.TestCase):
    def test_get_gui_html_contains_key_sections(self) -> None:
        html = gui.get_gui_html()

        self.assertIn("src=\"/logo.png\"", html)
        self.assertIn("alt=\"Quilloquy Studio logo\"", html)
        self.assertIn("id=\"searchInput\"", html)
        self.assertIn("id=\"viewOutlines\"", html)
        self.assertIn("id=\"toggleUtilities\"", html)
        self.assertIn("id=\"homeUtilities\"", html)
        self.assertIn("id=\"outlineShelf\"", html)
        self.assertIn("id=\"completedOutlineShelf\"", html)
        self.assertIn("id=\"bookShelf\"", html)
        self.assertIn("id=\"latestShelf\"", html)
        self.assertIn("id=\"genreShelves\"", html)
        self.assertIn("id=\"allBooksSection\"", html)
        self.assertIn("id=\"viewAllBooks\"", html)
        self.assertIn("id=\"viewAllBooksSecondary\"", html)
        self.assertIn("id=\"outlineSelect\"", html)
        self.assertIn("id=\"outlinePrompt\"", html)
        self.assertIn("id=\"outlineRevisions\"", html)
        self.assertIn("id=\"outlineName\"", html)
        self.assertIn("id=\"nowPlaying\"", html)
        self.assertIn("id=\"nowPlayingTitle\"", html)
        self.assertIn("id=\"nowPlayingSubtitle\"", html)
        self.assertIn("id=\"nowPlayingControls\"", html)
        self.assertIn("id=\"nowPlayingClose\"", html)
        self.assertIn("id=\"nowPlayingAutoplay\"", html)
        self.assertIn("id=\"nowPlayingHomeSlot\"", html)
        self.assertIn("id=\"nowPlayingGenreSlot\"", html)
        self.assertIn("id=\"nowPlayingOutlineSlot\"", html)
        self.assertIn("id=\"nowPlayingDetailSlot\"", html)
        self.assertIn("id=\"nowPlayingChapterSlot\"", html)
        self.assertIn("id=\"outlineDir\"", html)
        self.assertIn("id=\"outlineModel\"", html)
        self.assertIn("id=\"outlineBaseUrl\"", html)
        self.assertIn("id=\"generateOutline\"", html)
        self.assertIn("id=\"bookSelect\"", html)
        self.assertIn("id=\"chapterSelect\"", html)
        self.assertIn("id=\"homeView\"", html)
        self.assertIn("id=\"genreView\"", html)
        self.assertIn("id=\"genreBack\"", html)
        self.assertIn("id=\"outlineView\"", html)
        self.assertIn("id=\"outlineBack\"", html)
        self.assertIn("id=\"detailView\"", html)
        self.assertIn("id=\"detailBack\"", html)
        self.assertIn("id=\"workspacePanel\"", html)
        self.assertIn("id=\"detailSummary\"", html)
        self.assertIn("id=\"outlineWorkspace\"", html)
        self.assertIn("id=\"outlineWorkspaceAuthor\"", html)
        self.assertIn("id=\"outlineWorkspaceTone\"", html)
        self.assertIn("id=\"outlineEditor\"", html)
        self.assertIn("id=\"outlineSave\"", html)
        self.assertIn("id=\"outlineReload\"", html)
        self.assertIn("id=\"bookWorkspace\"", html)
        self.assertIn("id=\"bookWorkspaceCoverHeader\"", html)
        self.assertIn("id=\"bookContentHeading\"", html)
        self.assertIn("id=\"bookWorkspacePages\"", html)
        self.assertIn("id=\"bookProgressSummary\"", html)
        self.assertIn("id=\"bookProgressShelf\"", html)
        self.assertIn("id=\"chapterShelf\"", html)
        self.assertIn("id=\"readerPanel\"", html)
        self.assertIn("id=\"outlineWorkspaceSummary\"", html)
        self.assertIn("id=\"chapterAudio\"", html)
        self.assertIn("id=\"chapterVideo\"", html)
        self.assertIn("id=\"bookAudio\"", html)
        self.assertIn("id=\"bookCoverImage\"", html)
        self.assertIn("id=\"chapterCoverImage\"", html)
        self.assertIn("id=\"chapterView\"", html)
        self.assertIn("id=\"chapterBack\"", html)
        self.assertIn("id=\"chapterPageCount\"", html)
        self.assertIn("id=\"chapterSummary\"", html)
        self.assertIn("id=\"chapterProgressPanel\"", html)
        self.assertIn("id=\"chapterProgressSummary\"", html)
        self.assertIn("id=\"chapterProgressShelf\"", html)
        self.assertIn("id=\"chapterReaderBody\"", html)
        self.assertIn("id=\"chapterViewAudio\"", html)
        self.assertIn("id=\"chapterViewVideo\"", html)
        self.assertIn("id=\"chapterReaderCover\"", html)
        self.assertIn("id=\"generateBookCover\"", html)
        self.assertIn("id=\"generateChapterCovers\"", html)
        self.assertIn("id=\"bookWorkspaceCover\"", html)
        self.assertIn("id=\"chapterGenerateCover\"", html)
        self.assertIn("id=\"chapterCoverDir\"", html)
        self.assertIn("id=\"coverProgress\"", html)
        self.assertIn("id=\"coverProgressLabel\"", html)
        self.assertIn("id=\"gitPullRestart\"", html)
        self.assertIn("Pull latest changes", html)
        self.assertIn("Select a book before generating audio.", html)
        self.assertIn("Select a book before generating a cover.", html)
        self.assertIn("Select an outline before generating a book.", html)
        self.assertIn(
            "loadWorkspaceChapterContent(bookSelect.value, chapterSelect.value);",
            html,
        )
        self.assertIn(
            "outlineWorkspaceSummary.textContent = summaryLines.join(`\n`);",
            html,
        )
        self.assertIn("split(`\n`)", html)
        self.assertIn("handoffChapterAudioToDetail", html)
        self.assertIn("restoreChapterAudioToCard", html)
        self.assertIn("setCoverProgress(true", html)
        self.assertIn("buildGenerateBookPayload", html)
        self.assertIn("No preview available.", html)
        self.assertIn("stripMarkdownSymbols", html)
        self.assertIn("const formatInlineMarkdown = (value) => {", html)
        self.assertIn("formatInlineMarkdown(unorderedMatch[1])", html)
        self.assertIn("formatInlineMarkdown(orderedMatch[2])", html)
        self.assertIn("formatInlineMarkdown(headingMatch[2])", html)
        self.assertIn("formatInlineMarkdown(trimmed)", html)
        self.assertIn("const isHorizontalRule = (line) => line.trim() === '---';", html)
        self.assertIn("const isTableSeparator = (line) => {", html)
        self.assertIn("const parseTableCells = (line) => {", html)
        self.assertIn("tableHtml = '<table><thead><tr>';", html)
        self.assertIn("rel=\"noopener noreferrer\"", html)
        self.assertIn("sanitizeTitleForDisplay", html)
        self.assertIn("displayBookTitle", html)
        self.assertIn("displayChapterTitle", html)
        self.assertIn("hydrateAudioSource", html)
        self.assertIn("moveAudioToNowPlaying", html)
        self.assertIn("updateNowPlayingPlacement", html)
        self.assertIn("navigateToChapterDetail", html)
        self.assertIn("nowPlaying.addEventListener('click'", html)
        self.assertIn("nowPlayingClose.addEventListener('click', (event) => {", html)
        self.assertIn("event.preventDefault();", html)
        self.assertIn("event.stopPropagation();", html)
        self.assertIn("suppressNowPlayingNavigation();", html)
        self.assertIn("let suppressNowPlayingClick = false;", html)
        self.assertIn("shouldIgnoreNowPlayingClick", html)
        self.assertIn("playAutoplayChapter", html)
        self.assertIn("audio.preload = 'metadata';", html)
        self.assertIn("cleaned = cleaned.replace(/^[\\-–—]+\\s*/, '');", html)
        self.assertIn("renderCatalog", html)
        self.assertIn("filterEntries", html)
        self.assertIn("const genre = getPrimaryGenre(book);", html)
        self.assertIn("return `Genre: ${primary}`;", html)
        self.assertIn("const refreshMode = options.refreshMode || 'full';", html)
        self.assertIn("loadCatalog({ selectCurrent: false, refreshMode: 'books' });", html)
        self.assertIn("chapterBack.addEventListener('click', async () => {", html)
        self.assertIn(".workspace-actions {", html)
        self.assertIn("display: flex;", html)
        self.assertIn("width: auto;", html)
        self.assertIn("const resolveOutlinePath = () => {", html)
        self.assertIn("const workspacePath = outlineWorkspacePath.textContent.trim();", html)
        self.assertIn("const outlinePath = resolveOutlinePath();", html)
        self.assertIn("const loadBookProgress = async (bookDir) => {", html)
        self.assertIn("const renderBookProgress = (progress) => {", html)
        self.assertIn("const renderChapterProgress = (chapter) => {", html)
        self.assertIn(".book-card.cover-filled::before {", html)
        self.assertIn(".book-card.book-card-book {", html)
        self.assertIn(".book-card.book-card-book .card-description {", html)
        self.assertIn(".cover-header {", html)
        self.assertIn("border-radius: 24px 24px 0 0;", html)
        self.assertIn(".cover-header-content {", html)
        self.assertIn("card.className = 'book-card cover-filled';", html)
        self.assertIn("card.style.setProperty('--card-cover'", html)
        self.assertIn("coverUrl ? 'rgba(8, 12, 20, 0.55)'", html)
        self.assertIn("-webkit-line-clamp: 2;", html)
        self.assertIn("createCard(\n          book.title,\n          null,", html)
        self.assertIn("card.classList.add('selectable', 'book-card-book');", html)
        self.assertIn(".now-playing.with-cover .tag {", html)
        self.assertIn(".now-playing.with-cover .now-playing-settings {", html)
        self.assertIn(".now-playing.with-cover .now-playing-close {", html)
        self.assertIn("@media (max-width: 768px) {", html)
        self.assertIn("grid-auto-columns: minmax(300px, 66vw);", html)
        self.assertIn("scroll-snap-type: x mandatory;", html)
        self.assertIn("scrollbar-width: none;", html)
        self.assertIn("scroll-behavior: smooth;", html)
        self.assertIn("background: transparent;", html)
        self.assertIn("overflow-y: visible;", html)
        self.assertIn("--page-padding: 32px;", html)
        self.assertIn("margin-inline: calc(50% - 50vw);", html)
        self.assertIn("padding-inline: calc(50vw - 50% + var(--page-padding));", html)
        self.assertIn("scroll-padding-inline: calc(50vw - 50% + var(--page-padding));", html)
        self.assertIn(".now-playing-controls {", html)
        self.assertIn(".meta-line.markdown table {", html)
        self.assertIn(".reader-panel .reader-body table {", html)
        self.assertIn(".reader-panel .reader-body hr {", html)
        self.assertIn("const enableShelfWheelScroll = (shelf) => {", html)
        self.assertIn("shelf.scrollBy({ left: event.deltaY, behavior: 'smooth' });", html)
        self.assertIn("bindShelfWheelScroll();", html)
        book_shelf_index = html.index("id=\"bookShelf\"")
        outline_shelf_index = html.index("id=\"outlineShelf\"")
        self.assertLess(book_shelf_index, outline_shelf_index)
        reader_panel_index = html.index("id=\"readerPanel\"")
        media_panel_index = html.index("id=\"mediaPanel\"", reader_panel_index)
        reader_body_index = html.index("id=\"readerBody\"", reader_panel_index)
        self.assertLess(media_panel_index, reader_body_index)
        chapter_panel_index = html.index("id=\"chapterReaderPanel\"")
        chapter_cover_index = html.index("id=\"chapterReaderCover\"", chapter_panel_index)
        chapter_audio_index = html.index("id=\"chapterViewAudioBlock\"", chapter_cover_index)
        chapter_media_index = html.index("id=\"chapterMediaPanel\"", chapter_panel_index)
        chapter_body_index = html.index("id=\"chapterReaderBody\"", chapter_panel_index)
        self.assertLess(chapter_audio_index, chapter_media_index)
        self.assertLess(chapter_media_index, chapter_body_index)
        book_cover_index = html.index("id=\"bookWorkspaceCoverHeader\"")
        book_audio_index = html.index("id=\"bookAudioBlock\"", book_cover_index)
        book_meta_index = html.index("class=\"workspace-meta\"", book_cover_index)
        self.assertLess(book_audio_index, book_meta_index)
        search_bar_index = html.index("class=\"search-bar\"")
        now_playing_index = html.index("id=\"nowPlaying\"")
        self.assertLess(search_bar_index, now_playing_index)
        self.assertIn("Quilloquy", gui.__doc__ or "")

    def test_save_gui_html_writes_file(self) -> None:
        with self.subTest("write and read back"):
            from tempfile import TemporaryDirectory
            from pathlib import Path

            with TemporaryDirectory() as tmpdir:
                path = gui.save_gui_html(Path(tmpdir) / "gui.html")
                self.assertTrue(path.exists())
                self.assertIn(gui.GUI_TITLE, path.read_text(encoding="utf-8"))


if __name__ == "__main__":
    unittest.main()
